export const cliCases: Record<string, string[]> = {
  ready: ['ready'],
  timeline: ['timeline'],
  'project-state': ['project-state'],
  'project-validate': ['project-validate'],
  'project-backup': ['project-backup'],
  'project-restore': ['project-restore'],
  'project-sync': ['project-sync'],
  'project-list': ['project-list'],
  'epic-list': ['epic-list'],
  'work-list': ['work-list'],
  'sprint-list': ['sprint-list'],
  'epic-create': ['epic-create', '--id', 'epic', '--title', 'Epic', '--summary', '', '--goal', 'Goal'],
  'work-create': [
    'work-create',
    '--title',
    'Work',
    '--summary',
    '',
    '--acceptance',
    'done',
    '--scope-in',
    'src/**',
    '--scope-out',
    'dist/**',
    '--verify',
    'node --test',
  ],
  'work-transition': ['work-transition', '--id', 'item', '--to', 'ready'],
  'work-update': ['work-update', '--id', 'item'],
  'dependency-add': ['dependency-add', '--from', 'from', '--to', 'to'],
  'sprint-propose': [
    'sprint-propose',
    '--goal',
    'Goal',
    '--why',
    'Why',
    '--what',
    'What',
    '--how',
    'How',
    '--work-items',
    'item',
    '--done',
    'Done',
    '--verify',
    'node --test',
  ],
  'sprint-approve': ['sprint-approve', '--sprint', 'sprint', '--revision', 'revision'],
  'sprint-activate': ['sprint-activate', '--sprint', 'sprint', '--revision', 'revision'],
  'sprint-evidence-add': [
    'sprint-evidence-add',
    '--sprint',
    'sprint',
    '--kind',
    'verification',
    '--summary',
    'Summary',
    '--value',
    'Value',
  ],
  'sprint-close': ['sprint-close', '--sprint', 'sprint'],
  'sprint-remove-all': ['sprint-remove-all'],
  claim: ['claim', '--id', 'item'],
  'run-start': ['run-start', '--work-item', 'item'],
  'run-finish': ['run-finish', '--run', 'run', '--status', 'completed', '--reason', 'Done'],
  'evidence-add': [
    'evidence-add',
    '--run',
    'run',
    '--kind',
    'verification',
    '--summary',
    'Summary',
    '--value',
    'Value',
  ],
  'review-request': ['review-request', '--work-item', 'item', '--reviewer', 'reviewer'],
  'review-submit': ['review-submit', '--review', 'review', '--verdict', 'accepted', '--feedback', 'Accepted'],
};

type OperationFamily = { name: string; operations: string[] };

// Keep the adversarial matrix explicit: each row is an independently
// inspectable adapter family, rather than one aggregate loop whose coverage
// can be hidden by a single assertion or fixture.
export const operationFamilies: OperationFamily[] = [
  { name: 'ready and timeline', operations: ['ready', 'timeline'] },
  {
    name: 'project state and lifecycle',
    operations: ['project-state', 'project-validate', 'project-backup', 'project-restore', 'project-sync'],
  },
  { name: 'project listing', operations: ['project-list'] },
  { name: 'epic operations', operations: ['epic-list', 'epic-create'] },
  { name: 'work-item operations', operations: ['work-list', 'work-create', 'work-transition', 'work-update'] },
  { name: 'dependency operations', operations: ['dependency-add'] },
  {
    name: 'sprint and revision operations',
    operations: [
      'sprint-list',
      'sprint-propose',
      'sprint-approve',
      'sprint-activate',
      'sprint-evidence-add',
      'sprint-close',
      'sprint-remove-all',
    ],
  },
  { name: 'claim and run operations', operations: ['claim', 'run-start', 'run-finish', 'evidence-add'] },
  { name: 'review operations', operations: ['review-request', 'review-submit'] },
];
