export const CUSTOMER_ROLE = 'customer';
export const ADMIN_ROLE = 'admin';

export const SIGN_UP_CONFIRM_CODE = 'SIGN_UP_CONFIRM';
export const PASSWORD_RECOVERY_CODE = 'PASSWORD_RECOVERY';

export const roles = [CUSTOMER_ROLE, ADMIN_ROLE] as const;
export const oneTimeCodes = [
  SIGN_UP_CONFIRM_CODE,
  PASSWORD_RECOVERY_CODE,
] as const;

export type Role = (typeof roles)[number];
export type OneTimeCode = (typeof oneTimeCodes)[number];

export const INVALID_SIGN_UP_CONFIRM_CODE = 'INVALID_SIGN_UP_CONFIRM_CODE';
export const INVALID_PASSWORD_RECOVERY_CODE = 'INVALID_PASSWORD_RECOVERY_CODE';
export const INVALID_USERNAME_OR_PASSWORD = 'INVALID_USERNAME_OR_PASSWORD';
export const INVALID_USERNAME = 'INVALID_USERNAME';
export const INVALID_USER = 'INVALID_USER';
export const INVALID_CODE_TYPE = 'INVALID_CODE_TYPE';

export enum RoleEnum {
  ADMIN = 'admin',
  CUSTOMER = 'customer',
}

export enum ErrorCodesEnum {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_SIGN_UP_CONFIRM_CODE = 'INVALID_SIGN_UP_CONFIRM_CODE',
  INVALID_PASSWORD_RECOVERY_CODE = 'INVALID_PASSWORD_RECOVERY_CODE',
  INVALID_USERNAME_OR_PASSWORD = 'INVALID_USERNAME_OR_PASSWORD',
  INVALID_USERNAME = 'INVALID_USERNAME',
  INVALID_USER = 'INVALID_USER',
  INVALID_CODE = 'INVALID_CODE',
}
